### ISSUE TITLE
Handle `arm_custom_bypass` mode

### ISSUE THREAD

**Issue by eliciogiuseppe** [palazzem/econnect-python#102]
Esclusione personalizzata, andando a scegliere il sensore o la "zona" ovvero perimetrale, piano 1, 2 ecc da inserire/disinserire; quindi ad esempio quando attiviamo l'allarme includendo tutto potremmo escludere parte dei sensori (perchè c'è un guasto) o una intera zona, oppure attraverso una schermata includere/escludere determinate zone/sensori

esempio: clicco su esclusione, mi chiede quali zone voglio attivare/disattivare (non so se è possibile anche attivare determinati sensori ma questa è una cosa che viene fatta direttamente in fase di programmazione delle centrale creando una zona) e attiva magari il perimetrale con la zona giorno lasciando scoperta solo la zona notte e includendo il sensore del garage che si trova nella zona notte

**Comment by palazzem** [comment]
Translation (reworded with ChatGPT):

> "Custom exclusion feature needed: when selecting a sensor or "zone" such as perimeter, floor 1, floor 2, etc. to activate/deactivate. For instance, when turning on the alarm for the whole property, we should have the option to exclude a specific part of the house or a particular zone (via `arm_custom_bypass` mode)."

**Comment by palazzem** [comment]
Closing as this task has been moved in the HA Integration repository: https://github.com/palazzem/ha-econnect-alarm/issues/33
