### ISSUE TITLE
bug alarm panel when arming night sector

### ISSUE THREAD

**Issue by eliciogiuseppe** [palazzem/econnect-python#108]
**Describe the bug**

- Nella configurazione "fuori casa" inserisco 4 settori
- Nella configurazione "notte" inserisco un solo settore. 
- Attivo dal pannello alarm_control_panel.alarm_panel "fuori casa" e mi arma tutti e 4 i settori correttamente
- Attivo dal panello alarm_control_panel.alarm_panel "notte" e mi arma solo il settore che ho inserito.
- Il BUG è nel pannello poiché quando attivo "notte" risulta inserito "fuori casa" nonostante in realtà fosse inserito correttamente solo la zona notte.

Dalle immagini allegate si può notare come sia attiva solo la zona perimetrale (corrispondente alla zona notte) e come il pannello rilevi "fuori casa" 
<img width="1440" alt="Screenshot 2023-08-31 alle 12 15 50" src="https://github.com/palazzem/econnect-python/assets/58144107/fc7a570e-1b78-4964-8704-ed9ccef84568">
<img width="1440" alt="Screenshot 2023-08-31 alle 12 18 57" src="https://github.com/palazzem/econnect-python/assets/58144107/8dcc43ca-8918-4a90-83ec-d8a60dfc87e3">

**Expected behavior**
Quando attivo "fuori casa", il pannello alarm_control_panel.alarm_panel segnalerà "Fuori casa", mentre quando attivo "Notte", il pannello dovrà segnalare solo notte e non fuori casa come accade ora

**Environment**
 - Operating System (OS): 10.5
 - Supervisor 2023.08.1v
 - Home Assistant version: 2023.8.4

**Comment by palazzem** [comment]
The discussion about this bug has been moved here: https://github.com/palazzem/ha-econnect-alarm/issues/24

Moving as it refers to the Home Assistant integration that is now available in the other repository.

**Comment by palazzem** [comment]
Fixed in: https://github.com/palazzem/ha-econnect-alarm/pull/32

This bugfix will be available in the next HA Integration release (at the time of writing, the next version is 0.3.0).
