### ISSUE TITLE
Create a separate query for alarm_led, tamper_led and inputs_led

### ISSUE THREAD

**Issue by xtimmy86x** [palazzem/econnect-python#121]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
To improve readability towards integrations, I think it's better to separate the query for alarm_led, tamper_led and inputs_led as it can have 3 states instead of 2 like the rest of the alerts.

**Describe alternatives you've considered**
Add a query.leds or query.status function for retriev the leds status

**Additional context**
![Screenshot_2023-10-17_132931mod](https://github.com/palazzem/econnect-python/assets/76836856/0f4d4c05-d081-4602-a8aa-34cf8d29ca3e)

**Comment by palazzem** [comment]
Required for: https://github.com/palazzem/ha-econnect-alarm/issues/81

**Comment by palazzem** [comment]
Closed with https://github.com/palazzem/econnect-python/pull/118 and https://github.com/palazzem/econnect-python/pull/119/
