### ISSUE TITLE
Release the project on PyPI

### ISSUE THREAD

**Issue by palazzem** [palazzem/econnect-python#42]
### Overview

The project hit the first release (0.1.0 and 0.2.0). We should release it on PyPI so that it's easier to use and install.

**Comment by palazzem** [comment]
Hey @markin I saw you released my project in PyPI: https://pypi.org/project/elmo/

I'm planning to release the project in PyPI too, probably making some small changes but in the overall I'm pretty happy with the current status of the project. Considered it's already used in your home-automation [contribution](https://github.com/home-assistant/core/pull/31754/files#diff-d2a98e4969c1e91ad53f86f06b98fba2R482-R483), what if I integrate some of your changes in the upstream, and release it?

In this way we avoid having the same project published twice, and you can still contribute here whenever new features are added (or simply use mine when I add).

What do you think?

**Comment by markin** [comment]
Hi @palazzem, sorry if I published it but I've done it because I wanted to integrate with home-assistant. Let me know how you want to proceed, it is fine for me.

**Comment by palazzem** [comment]
Oh no worries! For me it's great that you find this project useful! Let's do that:
- Part of your contribution has been merged in #46 and #47 
- I'm missing the redirect part and the use of `/api/strings` endpoint
- As soon as I finish integrating #44 with very few changes, would be great if you can take a look and see if everything is alright for your contribution with home-assistant
- If everything is good, I'm going to publish this package so you can use this directly

On another topic, I was thinking to change the repository/package name to `econnect-python` because it's more meaningful. That said, I probably keep the code referencing as `elmo`. So you install `econnect-python` and you import `elmo` module. What do you think?

**Comment by markin** [comment]
Everything sounds good for me.

**Comment by palazzem** [comment]
I've renamed the project and now it's called `econnect-python`. The latest package (with your changes) is available in PyPI!

Here the official link: https://pypi.org/project/econnect-python/

I'm going to close this issue considering now the package is officially released and it includes your changes! Thank you!
