### ISSUE TITLE
Cannot retrieve system input exclusion status

### ISSUE THREAD

**Issue by davidecavestro** [palazzem/econnect-python#57]
Filled as per [this comment](https://github.com/palazzem/econnect-python/pull/55#pullrequestreview-421478063) of #55.

I need a way to get data about system inputs exclusion status.
This is a piece of info exposed by the server response to the [query](https://github.com/palazzem/econnect-python/blob/76915efc6fced0a166b5f832bf7f4786d2d7b1ad/elmo/api/client.py#L244-L261) along with other additional details.
Currently the query function simply ignores these details.
The same stands for sectors.

The first solution that comes into my mind is adding a `def rawquery(self, query, callback):` function which returns the result of invoking _callback_ passing the data as returned by the server.
(Probably there are more pythonic ways to achieve the same)

This is an excerpt of the whole set of attributes exposed by the server api respectively for sectors and inputs.

_SECTORS_
```
'Active' = {bool} False
'ActivePartial' = {bool} False
'Max' = {bool} False
'Activable' = {bool} True
'ActivablePartial' = {bool} False
'InUse' = {bool} True
'Id' = {int} 7010
'Index' = {int} 0
'Element' = {int} 1
'CommandId' = {int} 0
'InProgress' = {bool} False
```
_INPUTS_
```
'Alarm' = {bool} False
'MemoryAlarm' = {bool} False
'Excluded' = {bool} False
'InUse' = {bool} True
'IsVideo' = {bool} False
'Id' = {int} 26114
'Index' = {int} 0
'Element' = {int} 1
'CommandId' = {int} 0
'InProgress' = {bool} False
```

**Comment by palazzem** [comment]
I'm currently working in making `ElmoClient` lightweight with the only responsibility of handling the connection and making API calls. This means that I'm going to include the raw query and then let an external component (e.g. the `Device` object I'm adding in another branch) handle what is active/not active or included/excluded.

I will close this issue once all PRs are merged into `master`.

**Comment by palazzem** [comment]
#72 exposes the `excluded` field from the returned query. It doesn't implement your feature, but handles the use case of this specific GitHub issue. The full feature will be implemented in another PR.
