### ISSUE TITLE
Support e-connect for Homebridge/HomeKit

### ISSUE THREAD

**Issue by palazzem** [palazzem/econnect-python#77]
From @nickbolero:

> Ciao, scusa se sono fuori tema della discussione. Ma non sapevo come contattarti. Ho visto che hai creato un implementazione di econnect di elmo per Home Assistant, volevo chiederti se si potrebbe avere un qualcosa di simile per Homebridge/HomeKit in modo da integrarlo con la domotica di Apple Casa. Scusa ancora se sono off-topic. Puoi anche cancellare il mio intervento.

Translation:

> Hello, I apologize if I am off-topic in this discussion. But I didn't know how to contact you. I saw that you created an implementation of Elmo's econnect for Home Assistant, and I wanted to ask if it would be possible to have something similar for Homebridge/HomeKit in order to integrate it with Apple's smart home system. I apologize again if I am off-topic. You can also delete my comment.

**Comment by palazzem** [comment]
Ciao @nickbolero! Ho spostato la conversazione visto che anche altri potrebbero essere interessati all'argomento. Dunque questa libreria non offre una soluzione per integrare e-connect tramite Homebridge/HomeKit poiche` accede direttamente ai servizi web di e-connect per pilotare il sistema di allarme tramite le loro API (non pubbliche quindi soggette a modifiche).

Sfortunatamente non sono un esperto di Homebridge/HomeKit non avendo mai creato una integrazione per la domotica Apple, tuttavia posso investigare nei prossimi giorni e verificare se e` possibile e quanto tempo potrebbe volerci.

Tu per caso hai altri esempi di servizi che sono supportati sia da Home Assistant che dalla domotica Apple? Un tuo aiuto/feedback da utilizzatore finale potrebbe aiutarmi a velocizzare i task sopra indicati. Grazie in anticipo!

**Comment by nickbolero** [comment]
> Tu per caso hai altri esempi di servizi che sono supportati sia da Home Assistant che dalla domotica Apple? Un tuo aiuto/feedback da utilizzatore finale potrebbe aiutarmi a velocizzare i task sopra indicati. Grazie in anticipo!
>

Posso postarti come esempio questo del servizio di Lg:
**Home Bridge:** [https://github.com/nVuln/homebridge-lg-thinq#readme](url)
**Home Assistant:** [https://github.com/ollo69/ha-smartthinq-sensors](url)

>Sfortunatamente non sono un esperto di Homebridge/HomeKit non avendo mai creato una integrazione per la domotica Apple, tuttavia posso investigare nei prossimi giorni e verificare se e` possibile e quanto tempo potrebbe volerci.
>
Per prove o altro posso fare io da test.

**Comment by nickbolero** [comment]
Ciao @palazzem  novità per l’integrazione di Homebridge? Sei riuscito a capire se è fattibile?
Poi volevo chiederti se sapevi dirmi come fare per impostare il pin di inserimento/disinserimento nell’ integrazione di Home Assistant. Visto che lo stavo provando, esponendo poi tutte l’entità su HomeKit con l’integrazione apposita. Infatti ho postato anche sul canale ufficiale di Home Assistant quello dove si parla della tua integrazione, la richiesta di come inserire il pin in automatico.

**Comment by nickbolero** [comment]
> 1. Se non ho capito male, immagino che stai utilizzando Homebridge per tutti i tuoi dispositivi con integrazione per Homekit, mentre utilizzi Home Assistant solo per e-connect vista la mancata integrazione. E` corretto?

Si utilizzo Homebridge per quei dispositivi che non sono nativamente compatibili con HomeKit. E stavo cercando di utilizzare Home Assistant per esporre e-connect.




> 2. Vuoi inserire il PIN in automatico per una questione di semplicità, oppure perché è presente una limitazione nell'integrazione (e.g. il pannello dell'inserimento del PIN non funziona)?

No, la limitazione ce l’ho quando, una volta esposto tutte le entità di e-connect tra cui anche il pannello allarme che appare in HomeKit. Quando provo ad inserire uno stato, tipo Allarme Notte: non mi chiede da HomeKit di inserire il pin ma prova solo ad inserire quello stato, infatti quando lancio il comando vedo che su HomeAssistant il pannello allarmi si anima come se avessi premuto solo il tasto Allarme Notte senza inserire il pin. 
Da HomeAssistant se metto il codice e poi premo sullo stato che voglio inserire funziona tutto.
Per questo, ti avevo chiesto come fare per inserire in automatico il codice. La limitazione ce l ho su HomeKit. 
Comunque mi piacerebbe parlarti in privato.
Se ti fa piacere ti lascio la mia e-mail “ (nickbolero@gmail.com) così da scambiarci i contatti privatamente.
Ti chiedo anche, dopo aver letto questo messaggio di farmelo sapere così tolgo l’ email da questo post.

**Comment by palazzem** [comment]
Rimuovi pure la tua email, ti contatto in privato tra oggi e domani cosi` vedo se posso esserti di aiuto!

**Comment by nickbolero** [comment]
Ciao @palazzem voglio aggiornarti sulle prove che ho fatto:

- Allora, ho provato gli script come mi hai detto, funzionano con interruttori indipendenti, esponendo su homekit solo l'entita Allarm Pannel e script. Ma non è quello che chiedevo. Ti posto un immagine come esempio
- 
![Immagine WhatsApp 2023-04-22 ore 10 46 37](https://user-images.githubusercontent.com/54214273/233774113-6749b5af-ec00-4664-aa65-9af3ab8bfb8e.jpg)

- Quello che vorrei fare è inserire dall'interfaccia Allarm Pannel che posso esporre su homekit cosi da avere un qualcosa di piu coerente graficamente in homekit. 😛
Credo che dovrei creare un Allarm Pannel manuale come spiegato qui: [https://www.home-assistant.io/integrations/manual/](url) solo che non riesco a farlo funzionare.
Ti posto un altra immagine di esempio

![Immagine WhatsApp 2023-04-22 ore 10 46 36](https://user-images.githubusercontent.com/54214273/233774566-25dc89e7-2024-4a09-8350-19e4e99c15f1.jpg)

**Comment by palazzem** [comment]
Perdonami, è che per l'appunto non sono un esperto di Homekit o della domotica Apple quindi non mi rendo conto di cosa sia atteso o meno! Quindi se ho capito bene, ti vengono esposti tutti gli stati, ma non appena metti uno stato (esempio notte), allora viene correttamente lanciata la richiesta di attivazione ma, poiché il PIN non è inserito e non c'è modo di inserirlo, la richiesta fallisce e quindi non funziona.

Quello che dici è corretto ma non so bene come mai non vedi il pannello dell'allarme da Homekit nonostante l'entità venga correttamente esposta. Infatti, nella mia integrazione, il pannello di allarme è già creato e presente come entità ([codice](https://github.com/palazzem/core/pull/1/files#diff-950e17b371842c9fae2a6e6e294abec8ec1d19716139a67fc52dfc8bffd22bdcR53-R129)).

In teoria dovresti fare come dici te, ma temo che tra fare un pannello manuale o utilizzare quello offerto dalla mia integrazione non faccia molta differenza (se non vedi uno forse non ti farà vedere nemmeno l'altro?).

Giusto per fare una prova che però non ti consiglio di tenere attiva:
1. Dalla tua cartella di configurazione di HA, apri `custom_components/econnect_alarm/alarm_control_panel.py`.
2. Da li, in tutti gli stati dell'allarme, modifica `code=None` in `code=<IL_TUO_CODICE>` (non postare mai screenshot qua con il tuo codice presente).

Per fare un esempio, questa funzione:
```python
@set_device_state(STATE_ALARM_DISARMING)
async def async_alarm_disarm(self, code=None):
    """Send disarm command."""
    await self.hass.async_add_executor_job(self._device.disarm, code)
```

deve diventare:
```python
@set_device_state(STATE_ALARM_DISARMING)
async def async_alarm_disarm(self, code=<IL_TUO_CODICE>):  # ho cambiato solo questa riga
    """Send disarm command."""
    await self.hass.async_add_executor_job(self._device.disarm, code)
```

Fai questo cambio in tutte le funzioni dove vedi `code=None`, poi dimmi cosa succede in Homekit e quanto sei distante da quello che vorresti ottenere.

**Comment by palazzem** [comment]
Ah dimenticavo:
1. Sto dando per scontato che utilizzi la mia integrazione completa.
2. Fatta la modifica, devi riavviare Home Assistant completamente.

**Comment by nickbolero** [comment]
> Quello che dici è corretto ma non so bene come mai non vedi il pannello dell'allarme da Homekit nonostante l'entità venga correttamente esposta. Infatti, nella mia integrazione, il pannello di allarme è già creato e presente come entità ([codice](https://github.com/palazzem/core/pull/1/files#diff-950e17b371842c9fae2a6e6e294abec8ec1d19716139a67fc52dfc8bffd22bdcR53-R129)).

No, forse mi sono spiegato male. Allora il tuo pannello come anche quello che stavo cercando di creare in manuale. Vengono esposti e funzionano tranquillamente. O per meglio dire quando provo ad inserire uno di quei stati (Su HomeKit) che ti ho fatto lo screen. Il pannello su home assistant vedo che riaggisce. 
Cioè in poche parole e come se io da HomeAssistant premessi solo il tasto Attiva Notte senza codice, per tanto non succede niente.
Per questo ti avevo chiesto un modo tale che quando premo sul pannello di homeAssistant inserisci esempio: Attiva Notte si inserisca senza chiedere il codice. Cosa che succede realmente quando espongo il pannello su homekit. e provo da li ma senza risultato perche non viene inserito il codice in automatico alla pressione di quel tasto.


![Cattura](https://user-images.githubusercontent.com/54214273/233788953-2030f72f-18d9-44c6-a4de-cb95422dfb10.JPG)


> Fai questo cambio in tutte le funzioni dove vedi `code=None`, poi dimmi cosa succede in Homekit e quanto sei distante da quello che vorresti ottenere.

Ho fatto la modifica che mi hai segnalato ma dopo il riavvio home Assistant mi ha dato questi errori. Se vedi nel log il codice 12345 l'ho cambiato io per oscurarlo.
[home-assistant_2023-04-22T13-41-19.385Z.log](https://github.com/palazzem/econnect-python/files/11301504/home-assistant_2023-04-22T13-41-19.385Z.log)
e sul pannello dopo questa modifica sono scomparsi i tasti per iserire gli stati.

**Comment by palazzem** [comment]
Ah giusto perdonami, la modifica richiede i doppi apici (`" "`) quindi usando l'esempio che ti ho fatto deve diventare:

```python
@set_device_state(STATE_ALARM_DISARMING)
async def async_alarm_disarm(self, code="123456"):    # Basta aggiungere " "
    """Send disarm command."""
    await self.hass.async_add_executor_job(self._device.disarm, code)
```

**Comment by nickbolero** [comment]
Ok adesso ci siamo funziona cosi!! L'unica cosa non capisco perchè sul Allarm Pannel anche quando attivo notte come stato attivo mi vede sempre Allarme Fuori Casa.
Non dovrebbe mostrarmi la dicitura attiva Allarme Notte?
Volevo segnalarti che la tua integrazione manca l'iconcina di e-connect
![Cattura](https://user-images.githubusercontent.com/54214273/233795893-5216c750-cf23-4de3-ac53-217c5f72c554.JPG)

Per il discorso dello stato errato dell'inserimento hai idee?
Pensi sia fattibile avere questa integrazione direttamente in homebridge?
Ti posto alcune integrazioni generiche di allarme per homebridge:
[https://github.com/vectronic/homebridge-alarm-panel](url)
[https://github.com/MiguelRipoll23/homebridge-securitysystem](url)

**Comment by palazzem** [comment]
Perfetto! Per ora puoi lasciare così. Magari modifico l'integrazione in modo che dalla pagina di configurazione si possa inserire un codice di default. Così potrai fare tutto da interfaccia grafica senza modificare il codice direttamente.

Per quanto riguarda la dicitura, mi ricordo che ho avuto qualche limitazione in quello che HA mi forniva. Tuttavia, sono oramai passati 2 anni, quindi è il momento giusto per ricontrollare e vedere se posso migliorare il cambio di dicitura!

Per ricapitolare, ammesso che domani abbia tempo, posso integrare il tuo feedback:
1. Impostare il codice di default direttamente dalla pagina di configurazione dell'integrazione.
2. Verificare se ci sono limitazioni sulla dicitura Allarme Fuori Casa / Notte, ed in caso sistemare il bug.
3. Aggiungere l'icona di E-connect (pensavo di mettere [questa](https://user-images.githubusercontent.com/1560405/233796523-6d0b67e6-0e93-44c5-a884-18283ddfb067.png), che ne dici?).

A parte questi tre elementi, ora riesci ad utilizzare correttamente l'integrazione o hai notato altre cose che ti impediscono di utilizzarla?

Terminate queste modifiche, posso verificare la difficoltà nell'avere questa integrazione per Homebridge.

**Comment by nickbolero** [comment]
> 3\. Aggiungere l'icona di E-connect (pensavo di mettere [questa](https://user-images.githubusercontent.com/1560405/233796523-6d0b67e6-0e93-44c5-a884-18283ddfb067.png), che ne dici?).

Si, questa va benissimo.

> A parte questi tre elementi, ora riesci ad utilizzare correttamente l'integrazione o hai notato altre cose che ti impediscono di utilizzarla?

Si adesso per quello che devi fare va più che bene. Anche perché alla fine a me serve solo inserire lo stato Notte e Fuori Casa. Infatti volevo chiederti se cancello la parte di codice per l’ inserimento In Casa pensi che funziona lo stesso? Visto che su HomeKit mi espone anche questo tasto dell’ Allarm Pannel?
![image](https://user-images.githubusercontent.com/54214273/233800161-7eac2b79-de33-4ff1-8845-c5a331244c00.png)
A me serve vedere solo: Notte-Fuori Casa e Non Attivo per disinserirli.
Aspetto buone notizie per Homebridge.
Spero che quando approfondirai, saprai dirmi se si home kit è possibile mettere il codice dall’ Allarm Pannel di HomeKit.

**Comment by nickbolero** [comment]
Ciao @palazzem  novità? So che sicuramente sei stato impegnato. Spero di sentirti presto 😉

**Comment by palazzem** [comment]
Ciao @nickbolero ! Purtroppo sono stato fuori l'altra settimana e per lavoro saro` fuori anche questa. Posso darti qualche aggiornamento meta` settimana prossima quando torno!

Per quanto riguarda la tua domanda, se non ricordo male, l'alarm panel di Home Assistant espone l'opzione se il codice e la funzione e` definita. Pertanto se cancelli [questa parte del codice](https://github.com/palazzem/core/pull/1/files#diff-950e17b371842c9fae2a6e6e294abec8ec1d19716139a67fc52dfc8bffd22bdcR107-R116) dovrebbe disattivarla completamente.

Ti tengo aggiornato per la settimana prossima! A presto e fammi sapere se incontri altri problemi o bug con questa integrazione!

**Comment by nickbolero** [comment]
> Per quanto riguarda la tua domanda, se non ricordo male, l'alarm panel di Home Assistant espone l'opzione se il codice e la funzione e` definita. Pertanto se cancelli [questa parte del codice](https://github.com/palazzem/core/pull/1/files#diff-950e17b371842c9fae2a6e6e294abec8ec1d19716139a67fc52dfc8bffd22bdcR107-R116) dovrebbe disattivarla completamente.

ok faccio qualche prova e ti faccio sapere.



> Ti tengo aggiornato per la settimana prossima! A presto e fammi sapere se incontri altri problemi o bug con questa integrazione!

Aspetto tue notizie riguardo:

> Ok adesso ci siamo funziona cosi!! L'unica cosa non capisco perchè sul Pannello di Allarme anche quando attivo notte come stato attivo mi vede sempre Allarme Fuori Casa.

> 2\. Verificare se ci sono limitazioni sulla dicitura Allarme Fuori Casa / Notte, ed in caso sistemare il bug.

**Comment by palazzem** [comment]
This is now supported by the main Home Assistant Integration: https://github.com/palazzem/ha-econnect-alarm#homekit-integration.

Closing as it seems resolved at least for who is using Home Assistant.
